"""relationships fix

Revision ID: 13b819759a0b
Revises: 06d42fb946b3
Create Date: 2025-11-11 14:20:29.568487

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "13b819759a0b"
down_revision: Union[str, Sequence[str], None] = "06d42fb946b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
