"""Add business logic  models

Revision ID: 66ab7ea9acae
Revises: 88b86fc55d81
Create Date: 2025-11-05 21:21:33.374671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "66ab7ea9acae"
down_revision: Union[str, Sequence[str], None] = "88b86fc55d81"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("order", sa.Column("shipping_cost", sa.Float(), nullable=False))
    op.add_column("order", sa.Column("discount", sa.Float(), nullable=False))
    op.add_column("order", sa.Column("tax", sa.Float(), nullable=False))
    op.add_column("order", sa.Column("grand_total", sa.Float(), nullable=False))
    op.add_column(
        "order",
        sa.Column("shipping_method", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "order",
        sa.Column("tracking_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "order", sa.Column("estimated_delivery", sa.DateTime(), nullable=True)
    )
    op.add_column("order", sa.Column("shipped_at", sa.DateTime(), nullable=True))
    op.add_column("order", sa.Column("delivered_at", sa.DateTime(), nullable=True))
    op.add_column("order", sa.Column("cancelled_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order", "cancelled_at")
    op.drop_column("order", "delivered_at")
    op.drop_column("order", "shipped_at")
    op.drop_column("order", "estimated_delivery")
    op.drop_column("order", "tracking_number")
    op.drop_column("order", "shipping_method")
    op.drop_column("order", "grand_total")
    op.drop_column("order", "tax")
    op.drop_column("order", "discount")
    op.drop_column("order", "shipping_cost")
    # ### end Alembic commands ###
