"""made order address optional

Revision ID: 6c43b03e73e7
Revises: ac52b828f9b6
Create Date: 2025-11-18 01:44:09.647290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6c43b03e73e7"
down_revision: Union[str, Sequence[str], None] = "ac52b828f9b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "order", "shipping_address_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "order", "shipping_address_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
