"""Fix Order-Payment relationship

Revision ID: 88b86fc55d81
Revises: fe2aa5c230b3
Create Date: 2025-11-05 14:30:46.351621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "88b86fc55d81"
down_revision: Union[str, Sequence[str], None] = "fe2aa5c230b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("order_payment_id_fkey"), "order", type_="foreignkey")
    op.drop_column("order", "payment_id")
    op.add_column("payment", sa.Column("order_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "payment", "order", ["order_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "payment", type_="foreignkey")
    op.drop_column("payment", "order_id")
    op.add_column(
        "order",
        sa.Column("payment_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("order_payment_id_fkey"), "order", "payment", ["payment_id"], ["id"]
    )
    # ### end Alembic commands ###
