"""initial migration

Revision ID: a2f92b28619f
Revises: 
Create Date: 2025-11-17 09:34:22.246194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a2f92b28619f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("story")
    op.drop_column("user", "bio")
    op.drop_column("user", "full_name")
    op.drop_column("user", "profile_pic_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("profile_pic_url", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "user", sa.Column("full_name", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "user", sa.Column("bio", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_table(
        "story",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("story_url", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "post_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("caption", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("story_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("story_pkey")),
    )
    # ### end Alembic commands ###
