"""Made foreign keys non-nullable

Revision ID: ab4b4af47777
Revises: 66ab7ea9acae
Create Date: 2025-11-06 13:48:04.978923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ab4b4af47777"
down_revision: Union[str, Sequence[str], None] = "66ab7ea9acae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("address", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("cartitem", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "cartitem", "product_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column("delivery", "order_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("order", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("order", "store_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "order", "shipping_address_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column("orderitem", "order_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "orderitem", "product_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column("payment", "order_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("product", "store_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "product", "category_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "productimage", "product_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column("review", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("review", "product_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "rolepermissionlink", "role_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "rolepermissionlink",
        "permission_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column("store", "vendor_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "userpermissionoverride", "user_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "userpermissionoverride",
        "permission_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "userrolelink", "user_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "userrolelink", "role_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column("vendor", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "wishlistitem", "user_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "wishlistitem", "product_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "wishlistitem", "product_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "wishlistitem", "user_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("vendor", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "userrolelink", "role_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "userrolelink", "user_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "userpermissionoverride",
        "permission_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "userpermissionoverride", "user_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("store", "vendor_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "rolepermissionlink", "permission_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "rolepermissionlink", "role_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("review", "product_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("review", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "productimage", "product_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("product", "category_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("product", "store_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("payment", "order_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "orderitem", "product_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("orderitem", "order_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "order", "shipping_address_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("order", "store_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("order", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("delivery", "order_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("cartitem", "product_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("cartitem", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("address", "user_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
