"""messages conversation and delivery

Revision ID: ac52b828f9b6
Revises: a2f92b28619f
Create Date: 2025-11-17 12:14:30.319717

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "ac52b828f9b6"
down_revision: Union[str, Sequence[str], None] = "a2f92b28619f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
