"""initial migration

Revision ID: d87ea804be24
Revises: 
Create Date: 2025-11-18 14:06:13.563436

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "d87ea804be24"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
