"""add user profiles fields

Revision ID: ffb5df6a41bf
Revises: d87ea804be24
Create Date: 2025-11-18 14:47:08.695125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "ffb5df6a41bf"
down_revision: Union[str, Sequence[str], None] = "d87ea804be24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "user",
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "user",
        sa.Column("biography", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "user", sa.Column("gender", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column("user", sa.Column("date_of_birth", sa.DateTime(), nullable=True))
    op.create_index(op.f("ix_user_biography"), "user", ["biography"], unique=False)
    op.create_index(op.f("ix_user_first_name"), "user", ["first_name"], unique=False)
    op.create_index(op.f("ix_user_gender"), "user", ["gender"], unique=False)
    op.create_index(op.f("ix_user_last_name"), "user", ["last_name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_last_name"), table_name="user")
    op.drop_index(op.f("ix_user_gender"), table_name="user")
    op.drop_index(op.f("ix_user_first_name"), table_name="user")
    op.drop_index(op.f("ix_user_biography"), table_name="user")
    op.drop_column("user", "date_of_birth")
    op.drop_column("user", "gender")
    op.drop_column("user", "biography")
    op.drop_column("user", "last_name")
    op.drop_column("user", "first_name")
    # ### end Alembic commands ###
